##############################
# 本番定義 production
##############################
[production]
[production.logger_path]
# Server向けlogger定義
LOGGER_DEF_FILE = 'src/def/ibrUtilsLoggingHelper/logging_TimedRotateServer.json'
LOGGER_MSG_FILE = 'src/def/ibrUtilsLoggingHelper/config_MessageList.toml'

##############################
# リグレ定義 regression
##############################
[regression]
[regression.logger_path]
# Server向けlogger定義
LOGGER_DEF_FILE = 'src/def/ibrUtilsLoggingHelper/logging_TimedRotateServer.json'
LOGGER_MSG_FILE = 'src/def/ibrUtilsLoggingHelper/config_MessageList.toml'

# サーバドライブ依存パス定義
[regression.optional_path]
#CACHE_PATH ='W:\reference\src\cache'          #  アプリ側からは意識しない
LONGTERM_ACCUM_PATH ='W:\reference\src\work\longterm_accm'
SHORTTERM_ACCUM_PATH ='W:\reference\src\work\shortterm_accm'
TABLE_PATH = 'Z:\reference\src\table'
SHARE_RECEIVE_PATH = 'Z:\reference\src\share\receive'
SHARE_SEND_PATH = 'Z:\reference\src\share\send'
ARCHIVES_REFERNCE_SNAPSHOT_PATH = 'Z:\reference\src\archives\reference_snapshots'
ARCHIVES_REQUEST_SNAPSHOT_PATH = 'Z:\reference\src\archives\request_snapshots'
ARCHIVES_REFERENCE_DIFFS_PATH = 'Z:\reference\src\archives\reference_diffs'
ARCHIVES_CSV_FILES_PATH = 'Z:\reference\src\archives\csv_files'

##############################
# 開発機定義 develop
##############################
[develop]
[develop.logger_path]
# 開発機/local向けlogger定義
LOGGER_DEF_FILE = 'src/def/ibrUtilsLoggingHelper/logging_TimedRotate.json'
LOGGER_MSG_FILE = 'src/def/ibrUtilsLoggingHelper/config_MessageList.toml'

##############################
# local定義 local
##############################
[local]
[local.logger_path]
# 開発機/local向けlogger定義
LOGGER_DEF_FILE = 'src/def/ibrUtilsLoggingHelper/logging_TimedRotate.json'
LOGGER_MSG_FILE = 'src/def/ibrUtilsLoggingHelper/config_MessageList.toml'

[local.decision_table_path]
DECISION_TABLE_PATH = 'src/def/decision_table'

# サーバドライブ依存パス定義
[local.optional_path]
#CACHE_PATH ='W:\reference\src\cache'          #  アプリ側からは意識しない
LONGTERM_ACCUM_PATH ='src/work/longterm_accm'
SHORTTERM_ACCUM_PATH ='src/work/shortterm_accm'
TABLE_PATH = 'src/table'
SHARE_RECEIVE_PATH = 'src/share/receive'
SHARE_SEND_PATH = 'src/share/send'
ARCHIVES_REFERNCE_SNAPSHOT_PATH = 'src/archives/reference_snapshots'
ARCHIVES_REQUEST_SNAPSHOT_PATH = 'src/archives/request_snapshots'
ARCHIVES_REFERENCE_DIFFS_PATH = 'src/archives/reference_diffs'
ARCHIVES_CSV_FILES_PATH = 'src/archives/csv_files'

