#############################
# 本番定義 production
#############################
[production]
[production.x]
x = 'x'

############################
# リグレ定義 regression
#############################
[regression]
[regression.x]
x = 'x'

#############################
# 開発定義 develop
#############################
[develop]
[develop.x]
x = 'x'

#############################
# local定義 local
#############################
[local]
[local.decision_table_file]
DECISION_PRE_BOOK_NAME = '受付処理Facade一覧.xlsx'
DECISION_PRE_SHEET_NAME = '受付処理Facade一覧'
#DECISION_PTN_BOOK_NAME = 'パターン編集処理Facade一覧.xlsx'
#DECISION_PTN_SHEET_NAME = 'パターン編集処理Facade一覧'

# sample
[local.decision_table_book_name]
DECISION_TABLE_BOOK_NANE = 'decision_table.xlsx'

[local.preparation_sample_data]
PREPARATION_SAMPLE_DATA = 'data_sample1.xlsx'

# 受付Facade
[local.import_editor_facade]
FACADE_IMPORT_PATH = 'src.model.facade.preparation_editor_facade'

# パターン編集Facade
#[local.import_editor_facade]
#FACADE_IMPORT_PATH = 'src.model.facade.pattern_editor_facade'