[DEF_IBRDEV_MSGS]
#########################################
# 正常系定義 IBRDEV-I-7桁
#########################################
"IBRDEV-I-0000001" = "起動しました"
"IBRDEV-I-0000002" = "正常終了しました"
"IBRDEV-I-0000003" = "定義取得しました"
"IBRDEV-I-0000004" = "Mutexによる多重制御を開始します"
"IBRDEV-I-0000005" = "Mutexによる多重制御を終了しました"

#########################################
# エラー系定義 IBRDEV-E-7桁
#########################################
"IBRDEV-E-0000001" = "異常終了しました"
"IBRDEV-E-0000100" = "ValidationErrorが発生しました"

#########################################
# ワーニング系定義 IBRDEV-E-7桁
#########################################
"IBRDEV-W-0000001" = "何かしら要注意です"
